AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI-Query-Generator lambda function with Provisioned Concurrency


Globals:
  Function:
    Timeout: 900
    MemorySize: 10240
    Runtime: python3.8
    Architectures:
      - x86_64

Resources:
  AIQuestionGenerator:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 044393563897.dkr.ecr.eu-west-1.amazonaws.com/lambda-container-question-generator:dev-2.0

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src
      DockerTag: demo

